using System;
using System.Collections.Generic;
using System.Text;

namespace SharedNavigation.NETStandard
{
    public interface INavigationView<T> where T : class, INavigationViewModel, new()
    {
        void RegisterNavigationByAutoGenerated(T viewModel, INavigationAction defaultNavigationAction);
    }
}
