using System;
using System.Threading.Tasks;

namespace SharedNavigation.NETStandard.Test.Assembly
{
    public class FinderViewModel : INavigationViewModel
    {
        [InjectNavigation]
        public INavigationCommand<SimpleViewModel> PushCommand { get; set; } = new NavigationCommand<SimpleViewModel>();

        public void RestoreState(byte[] state)
        {
            throw new NotImplementedException();
        }

        public byte[] SaveState()
        {
            throw new NotImplementedException();
        }
    }

    #region For isNavigationView
    public interface IFinderView1 { }

    public class FinderView2 { }

    public class FinderView3 : IFinderView1 { }

    public class FinderView4 : IFinderView1
    {
        public void Method() { }
    }

    public class FinderView5 : INavigationView<SimpleViewModel>
    {
        public void RegisterNavigationByAutoGenerated(SimpleViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public interface IExtendNavigationView : INavigationView<FinderViewModel> { }

    public class FinderView6 : IExtendNavigationView
    {
        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView7 : FinderView6 { }
    #endregion

    #region For findNavigateMethods
    public class FinderView20 : INavigationView<FinderViewModel>
    {
        public Task PushAsync(FinderViewModel finderViewModel)
        {
            return Task.CompletedTask;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView21 : INavigationView<FinderViewModel>
    {
        [Navigate(nameof(FinderViewModel.PushCommand))]
        public Task PushAsync()
        {
            return Task.CompletedTask;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView22 : INavigationView<FinderViewModel>
    {
        [Navigate(nameof(FinderViewModel.PushCommand))]
        public Task PushAsync(FinderViewModel viewModel1, FinderViewModel viewModel2)
        {
            return Task.CompletedTask;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView23 : INavigationView<FinderViewModel>
    {
        [Navigate(nameof(FinderViewModel.PushCommand))]
        public bool PushAsync(FinderViewModel viewModel)
        {
            return false;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView24 : INavigationView<FinderViewModel>
    {
        [Navigate(nameof(FinderViewModel.PushCommand))]
        public Task<bool> PushAsync(FinderViewModel viewModel)
        {
            return Task.FromResult(false);
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView25 : INavigationView<FinderViewModel>
    {
        [Navigate(nameof(FinderViewModel.PushCommand))]
        public Task PushAsync(FinderViewModel viewModel)
        {
            return Task.CompletedTask;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }
    #endregion

    #region For findCanNavigateMethods
    public class FinderView40 : INavigationView<FinderViewModel>
    {
        public bool CanPush(FinderViewModel finderViewModel)
        {
            return false;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView41 : INavigationView<FinderViewModel>
    {
        [CanNavigate(nameof(FinderViewModel.PushCommand))]
        public bool CanPush()
        {
            return false;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView42 : INavigationView<FinderViewModel>
    {
        [CanNavigate(nameof(FinderViewModel.PushCommand))]
        public bool CanPush(FinderViewModel viewModel1, FinderViewModel viewModel2)
        {
            return false;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView43 : INavigationView<FinderViewModel>
    {
        [CanNavigate(nameof(FinderViewModel.PushCommand))]
        public string CanPush(FinderViewModel viewModel)
        {
            return string.Empty;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView44 : INavigationView<FinderViewModel>
    {
        [CanNavigate(nameof(FinderViewModel.PushCommand))]
        public bool CanPush(FinderViewModel viewModel)
        {
            return false;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }
    #endregion

    #region For findInjectProperty
    public class FinderViewModel60 : INavigationViewModel
    {
        public void RestoreState(byte[] state)
        {
            throw new NotImplementedException();
        }

        public byte[] SaveState()
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView60 : INavigationView<FinderViewModel60>
    {
        [Navigate("PushCommand")]
        public Task PushAsync(FinderViewModel60 viewModel)
        {
            return Task.CompletedTask;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel60 viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderViewModel61 : INavigationViewModel
    {
        public string PushCommand { get; }

        public void RestoreState(byte[] state)
        {
            throw new NotImplementedException();
        }

        public byte[] SaveState()
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView61 : INavigationView<FinderViewModel61>
    {
        [Navigate(nameof(FinderViewModel61.PushCommand))]
        public Task PushAsync(FinderViewModel61 viewModel)
        {
            return Task.CompletedTask;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel61 viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderViewModel62 : INavigationViewModel
    {
        public INavigationCommand<FinderViewModel62> PushCommand { get; }

        public void RestoreState(byte[] state)
        {
            throw new NotImplementedException();
        }

        public byte[] SaveState()
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView62 : INavigationView<FinderViewModel62>
    {
        [Navigate(nameof(FinderViewModel62.PushCommand))]
        public Task PushAsync(FinderViewModel62 viewModel)
        {
            return Task.CompletedTask;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel62 viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderViewModel63 : INavigationViewModel
    {
        [InjectNavigation]
        public INavigationCommand<FinderViewModel63> PushCommand { get; }

        public void RestoreState(byte[] state)
        {
            throw new NotImplementedException();
        }

        public byte[] SaveState()
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView63 : INavigationView<FinderViewModel63>
    {
        [Navigate(nameof(FinderViewModel63.PushCommand))]
        public Task PushAsync(FinderViewModel63 viewModel)
        {
            return Task.CompletedTask;
        }

        public void RegisterNavigationByAutoGenerated(FinderViewModel63 viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }
    #endregion

    #region For findRegisterNavigation
    public class FinderView80 : INavigationView<FinderViewModel>
    {
        void INavigationView<FinderViewModel>.RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }

    public class FinderView81 : INavigationView<FinderViewModel>
    {
        public void RegisterNavigationByAutoGenerated(FinderViewModel viewModel, INavigationAction defaultNavigationAction)
        {
            throw new NotImplementedException();
        }
    }
    #endregion
}
