using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SharedNavigation.NETStandard.Fody
{
    internal static class Constant
    {
        internal const string TargetNameSpace = "SharedNavigation.NETStandard";
        internal const string SystemThreadingTasksNameSpace = "System.Threading.Tasks";

        internal const string NavigationActionInterfaceFullName = "SharedNavigation.NETStandard.INavigationAction";
        internal const string NavigationActionNavigateAsyncName = "NavigateAsync";
        internal const string NavigationActionCanNavigateName = "CanNavigate";

        internal const string NavigationViewInterfaceFullName = "SharedNavigation.NETStandard.INavigationView";
        internal static readonly GenericType NavigationView =
            new GenericType(
                "SharedNavigation.NETStandard", "INavigationView", 1
            );
        internal const string NavigationViewRegisterNavigationByAutoGeneratedName =
            "RegisterNavigationByAutoGenerated";

        internal const string NavigationViewModelInterfaceFullName = "SharedNavigation.NETStandard.INavigationViewModel";

        internal static readonly GenericType NavigationCommand =
            new GenericType(
                "SharedNavigation.NETStandard", "INavigationCommand", 1
            );
        internal const string NavigationCommandNavigationActionName = "NavigationAction";

        internal const string NavigateAttributeFullName = "SharedNavigation.NETStandard.NavigateAttribute";
        internal const string CanNavigateAttributeFullName = "SharedNavigation.NETStandard.CanNavigateAttribute";

        internal class GenericType
        {
            public string NameSpace { get; }
            public string Name { get; }
            public string FullName => $"{NameSpace}.{Name}";
            public int TypeParameterCount { get; }

            public GenericType(string nameSpace, string name, int typeParameterCount)
            {
                NameSpace = nameSpace;
                Name = name;
                TypeParameterCount = typeParameterCount;
            }
        }
    }
}
